### PR TITLE
Updated UI to be fully responsive for mobile/tablet (#4)

### PR DESCRIPTION
**Pull request by nbfontana**
Fixes: video-player, header and videos-playlist responsiveness #4

### CODE REVIEW

**Review by SamirHodzic — CHANGES_REQUESTED** [review]
Could you please resubmit it without the code formatting changes? It makes it very difficult for me to see what code you've changed/added in the diff.

**Comment by nbfontana** [comment]
@SamirHodzic if the ".editorconfig" has an "indent_size = 2" shouldn't I respect it? IntelliJ and WebStorm do automatic configurations based on ".editorconfig" files in the project. Sorry for that, should I change it to 4 spaces as tabs?

**Comment by SamirHodzic** [comment]
Whops, seems like my bad, sorry. There should be `indent_style = space` istead of `tab`. Pushed updated .editorconfig.

**Comment by nbfontana** [comment]
@SamirHodzic I believe it is better now, let me know if something is wrong

**Comment by SamirHodzic** [comment]
Really good job, just few more comments. Maybe we should hide `Now playing` on small devices when a video is minimized, and move buttons a bit because on this right part is being overlapped.

screen shot 2017-10-09 at 18 29 16

Maybe to remove this option to enlarge video on mobile too.

screen shot 2017-10-09 at 18 34 05

**Comment by nbfontana** [comment]
@SamirHodzic I did the video-player adjustments, but the enlarge video button on mobile is a little bit more tricky, I would consider adding another Issue just for that because we have some behaviors when the user leaves full screen mode. What do you think about it?

**Comment by SamirHodzic** [comment]
Sure thing, make another issue for it.

**Comment by nbfontana** [comment]
@SamirHodzic Feel free to merge this when you're ready, so I can start working on other Issues

**Review by SamirHodzic — APPROVED** [review]
Thank you 👍

**Pull request merged**
